<a href="https://colab.research.google.com/github/radsrei/Caderno-Faculdade/blob/main/DS_Catolica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

05/08 - Aula NumPy
Utilizar Numpy para operações númericas eficientes, manipulação de arrays e fundamentos para Ciência de Dados

#Parte1: Introdução

In [ ]:
import numpy as np


###Listas

In [ ]:
#Array 1D com uma lista Python
lista = [1,2,3,4,5]
array_de_lista = np.array(lista)
print(array_de_lista)
print(array_de_lista.dtype)
array_de_lista

[1 2 3 4 5]
int64


array([1, 2, 3, 4, 5])

In [ ]:
#Array 2D com lista Python

lista_de_listas = [[1,2,3],[4,5,6],[7,8,9]]
array_de_listas = np.array(lista_de_listas)
print(array_de_listas)
array_de_listas

In [ ]:
# com zero
zero_ld = np.zeros(10)
print(zero_ld)
zero_ld

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# com uns
ones_ld = np.ones(10)
print(ones_ld)
ones_ld

In [ ]:
# com vazia
empty_ld = np.empty(10)
print(empty_ld)
empty_ld


In [ ]:
# shape é uma tupla
zeros_2d = np.zeros((3,3))
print(zeros_2d)
zeros_2d

In [ ]:
# com valor especifico
full_array = np.full((3,3), 7)
print(full_array)
full_array

###Sequências Numérias

In [ ]:
# np.arrange()

seq_1 = np.arange(10)
print(seq_1)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18]


In [ ]:
#[start:stop:step]
seq_2 = np.arange(0, 20, 2)
print(seq_2)

In [ ]:
#[start:stop:num_elements]

linspace_array = np.linspace(0, 10, 5)
print(linspace_array)

In [ ]:
#np.random.rand()
rand_array = np.random.rand(4)
print(rand_array)

[0.63151745 0.67351601 0.54582258 0.58715149]


In [ ]:
# np.random.randint(): [low:high:size]
randint_array = np.random.randint(0, 10, 5)
print(randint_array)

[6 0 1 5 1]


##Atributos importantes de um Array

In [ ]:
#dtype: tipo de dados dos elementos
array_de_lista.dtype

In [ ]:
#astype: mudar o tipo de dados dos elementos
rand_array_int = rand_array.astype(np.int64)
rand_array_int

array([0, 0, 0, 0])

In [ ]:
#shape: dimensões da tabela
randint_array.shape

(5,)

In [ ]:
#ndim: numero de dimensões array
rand_array.ndim

1

In [ ]:
#size: numero de elementos
rand_array.size

In [ ]:
# nbytes: tamanho total do array em bytes
rand_array.nybets

NameError: name 'rand_array' is not defined

#Parte 2: Operações com Array


##Operações Aritméticas


In [ ]:
arr_op1 = np.array([1,2,3])
arr_op2 = np.array([4,5,6])

#soma de arrays
arr_op1 + arr_op2

array([5, 7, 9])

In [ ]:
#multipliacação de array
arr_op1 * arr_op2

array([ 4, 10, 18])

In [ ]:
# Operações escalares
print(arr_op2 + 10)
print(arr_op2 * 10)
print(arr_op1 / 2)

[14 15 16]
[40 50 60]
[0.5 1.  1.5]


##Indexação

In [ ]:
# acessando um elemento (1D)
arr_1d = np.array(0,20)
print(arr_1d)

print('Primeiro Elemento índice 0:', arr_1d[0])
print('Décimo Eleme to índice 9:',arr_1d[9])
print('Ultimo Elemento índice -1:', arr_1d[-1])

In [ ]:
# acessando um elemento (2D)
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Matriz: \n', matriz)

Matriz: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# linha, coluna
print(matriz[0,1])
print(matriz[2,2])

##Slicing

In [ ]:
# [start:stop:step] - Stop é exclusivo

print('Elementos do índice 2 ao 5:',arr_1d[2:6])
print('Elementos do inicio até o índice 5', arr_1d[:6])
print('Elementos do índice 2 até o final', arr_1d[2:])
print('Elementos com passo de 2:', arr_1d[::2])
print('Elementos em ordem reversa:', arr_1d[::-1])

In [ ]:
#Slicing e atribuição
arr_1d_mod = np.copy(arr_1d)
arr_1d_mod[0:3] = 99
print(arr_1d_mod)

NameError: name 'arr_1d' is not defined

In [ ]:
#slicing/atribuição nd
#[Star_row:stop_row, start_col:stop_col]
matriz[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [ ]:
#todas as linhas, coluna específica
matriz[:,2]

array([3, 6, 9])

In [ ]:
#linha especifica, todas as colunas
matriz[1,:]

array([4, 5, 6])

In [ ]:
#selecionar linhas especificar e todas as colunas
matriz[[0,2],:]

# Parte 3: Biblioteca Panda
## Pandas é uma ferramenta essencial para a manipulação de dados em Python. Vamos explorar 2 estruturas de dados em pandas:
**Series**
**DataFrames**

## Etapa 1: Com dados digitados

In [1]:
import pandas as pd

### Criando Series

Uma Serie é um array unidimensonal com rótulos (índices)

In [3]:
# Criar uma Serie a partir de uma lista

s = pd.Series([10,20,30,40,50])
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64


## Acessando os valores e índices

In [4]:
# acessando os valores da series
print(s.values)

[10 20 30 40 50]


In [5]:
# acessando os indices da series
print(s.index)

RangeIndex(start=0, stop=5, step=1)


## Criando uma Serie com índices Personalizados

In [8]:
s2 = pd.Series([10,20,30,40,50], index=['a','b','c','d','e'])
print(s2)

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [9]:
s2[s2>4]

,0
a,10
b,20
c,30
d,40
e,50


## DataFrame

Uma estrutura de dados tabular bidimensional com eixos rotulados

In [11]:
# Criando um DataFrame a partir de um dicionário
dados = {'Nome': ['Alice', 'Bob', 'Charlie', 'David'],
         'Idade': [25, 30, 35, 40],
         'Cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Porto Alegre']}

In [12]:
df_br = pd.DataFrame(dados)
print(df_br)

      Nome  Idade          Cidade
0    Alice     25       São Paulo
1      Bob     30  Rio de Janeiro
2  Charlie     35  Belo Horizonte
3    David     40    Porto Alegre


##Acessar e manipular dados no DataFrame

In [13]:
# visualização das linhas iniciais
print(df_br.head(3))

      Nome  Idade          Cidade
0    Alice     25       São Paulo
1      Bob     30  Rio de Janeiro
2  Charlie     35  Belo Horizonte


In [14]:
# visualizar linhas finais
print(df_br.tail(2))

      Nome  Idade          Cidade
2  Charlie     35  Belo Horizonte
3    David     40    Porto Alegre


In [15]:
# visualizar linha aleatória
print(df_br.sample(2))

      Nome  Idade          Cidade
2  Charlie     35  Belo Horizonte
0    Alice     25       São Paulo


### Acessando Colunas ou mudando colunas de posição

In [16]:
# Acessar a coluna 'Cidade'
print(df_br['Cidade'])

0         São Paulo
1    Rio de Janeiro
2    Belo Horizonte
3      Porto Alegre
Name: Cidade, dtype: object


In [17]:
# Mudar colunas de posição
df2_br = pd.DataFrame(dados, columns=['Cidade', 'Nome', 'Idade'])
print(df2_br)

           Cidade     Nome  Idade
0       São Paulo    Alice     25
1  Rio de Janeiro      Bob     30
2  Belo Horizonte  Charlie     35
3    Porto Alegre    David     40


##Adicionar uma nova Coluna

In [ ]:
df2_br['Altura'] = [1.65, 1.70, 1.75, 1.80]
print(df2_br)

##Adicionar uma coluna do tipo Booleano

In [ ]:
# Coluna boolean
df2_br['>10']=df2_br['Idade']>10
print(df2_br)

##Exclusão ou modificação de dados (linhas, colunas)

In [ ]:
# Excluir
df2_br.drop('Altura', axis=1, inplace=True)
print(df2_br)