<a href="https://colab.research.google.com/github/radsrei/Caderno-Faculdade/blob/main/DS_Catolica.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

05/08 - Aula NumPy
Utilizar Numpy para operações númericas eficientes, manipulação de arrays e fundamentos para Ciência de Dados

#Parte1: Introdução

In [2]:
import numpy as np


###Listas

In [5]:
#Array 1D com uma lista Python
lista = [1,2,3,4,5]
array_de_lista = np.array(lista)
print(array_de_lista)
print(array_de_lista.dtype)
array_de_lista

[1 2 3 4 5]
int64


array([1, 2, 3, 4, 5])

In [ ]:
#Array 2D com lista Python

lista_de_listas = [[1,2,3],[4,5,6],[7,8,9]]
array_de_listas = np.array(lista_de_listas)
print(array_de_listas)
array_de_listas

In [8]:
# com zero
zero_ld = np.zeros(10)
print(zero_ld)
zero_ld

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# com uns
ones_ld = np.ones(10)
print(ones_ld)
ones_ld

In [ ]:
# com vazia
empty_ld = np.empty(10)
print(empty_ld)
empty_ld


In [ ]:
# shape é uma tupla
zeros_2d = np.zeros((3,3))
print(zeros_2d)
zeros_2d

In [ ]:
# com valor especifico
full_array = np.full((3,3), 7)
print(full_array)
full_array

###Sequências Numérias

In [7]:
# np.arrange()

seq_1 = np.arange(10)
print(seq_1)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[10 12 14 16 18]


In [ ]:
#[start:stop:step]
seq_2 = np.arange(0, 20, 2)
print(seq_2)

In [ ]:
#[start:stop:num_elements]

linspace_array = np.linspace(0, 10, 5)
print(linspace_array)

In [9]:
#np.random.rand()
rand_array = np.random.rand(4)
print(rand_array)

[0.63151745 0.67351601 0.54582258 0.58715149]


In [15]:
# np.random.randint(): [low:high:size]
randint_array = np.random.randint(0, 10, 5)
print(randint_array)

[6 0 1 5 1]


##Atributos importantes de um Array

In [ ]:
#dtype: tipo de dados dos elementos
array_de_lista.dtype

In [12]:
#astype: mudar o tipo de dados dos elementos
rand_array_int = rand_array.astype(np.int64)
rand_array_int

array([0, 0, 0, 0])

In [16]:
#shape: dimensões da tabela
randint_array.shape

(5,)

In [14]:
#ndim: numero de dimensões array
rand_array.ndim

1